name: Schedule PHP Script

on:
  schedule:
    - cron: '30 7/8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Run PHP Script
        run: |
          php script.php
        env:
          Tokeni: ${{ secrets.TOKEN }}
          LO: ${{ secrets.LO }}
          
      - name: Configure Git and Push
        run: |
          git config --local user.email "thisisman1b@gmail.com"
          git config --local user.name "FreeForAllN"
          git add -A
          git commit -m "🚀 Sub Update - $(date '+%Y-%m-%d %H:%M:%S')" --allow-empty
          git push
          
